language: python
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
python:
    - "3.6"
env:
    global:
     - TRAVIS=true
     - DJANGO_SETTINGS_MODULE="djangoblog.settings"

install:
  - pip install -r requirements.txt
#  - pip install python-coveralls
#  - pip install coverage codecov

before_script:
    - mysql -e 'CREATE DATABASE `django_east` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
    - python manage.py makemigrations
    - python manage.py migrate
#    - python manage.py collectstatic --noinput
#    - python manage.py compress --force

script:
#    - python manage.py test

#after_success:
#    - coveralls
#    - codecov
