language: python
sudo: enabled
services:
    - mysql
python:
    - "3.6"
env:
    global:
     - TRAVIS=true
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS django_east DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
#    - mv configs.example.json configs.json
# command to install dependencies
install:
    - pip install -r requirements.txt
script:
    - python manage.py makemigrations
    - python manage.py migrate

