language: python
services:
    - mysql
python:
    - "3.6"
env:
    global:
     - TRAVIS=true
     - DJANGO_SETTINGS_MODULE="djangoblog.settings"

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage codecov

before_script:
    - mysql -e 'CREATE DATABASE `django_east` /*!40100 DEFAULT CHARACTER SET utf8 */;'
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - python manage.py compress --force

script:
    - coverage run manage.py test

after_success:
    - coveralls
    - codecov
