language: python
sudo: enabled
services:
    - mysql
python:
    - "3.6.2"
env:
    global:
     - TRAVIS=true
before_install:
    - mysql -e 'show variables like "%char%";'
    - mysql -e 'SET character_set_database = utf8;'
    - mysql -e 'CREATE DATABASE `django_east`;'
    - mysql -e 'show variables like "%char%";'

#    - mv configs.example.json configs.json
# command to install dependencies
install:
    - pip install -r requirements.txt
script:
#    - cp configs.example.json configs.json
    - python manage.py makemigrations
    - python manage.py migrate

